exclude:
  - npm-packages-offline-cache
  - node_modules
  - Gemfile
  - Gemfile.lock
  - package.json
  - yarn.loc
  - api-model
  - api
  - census
  - cluster
  - model
  - parser
  - persistence-model
  - persistence
  - platform-test
  - project
  - publication
  - query
  - target
  - validation

sass:
  sass_dir: _sass