---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "check-digit.fullname" . }}
  labels:
    app: {{ template "check-digit.name" . }}
    chart: {{ template "check-digit.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
    app: {{ template "check-digit.name" . }}
    release: {{ .Release.Name }}


---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador-chk-digit
  name: ambassador-chk-digit
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v0
      kind: Mapping
      name: check_digit_mapping
      prefix: /v2/public/uli/checkDigit/
      service: hmda-check-digit:9091
spec:
  type: NodePort
  ports:
  - name: ambassador-chk-digit
    port: 80
    targetPort: 80
  selector:
    service: ambassador-chk-digit