# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
jobs:
  # third cron
  - name: newman-tests
    image:
      repository: dtr.cfpb.gov/hmda/newman-automation
      tag: filingTimer
      imagePullPolicy: Always
    # optional env vars
    env:
    - name: HOST_FILING
      value:
    - name: HOST_ADMIN
      value:
    - name: HOST_PUBLIC
      value:
    - name: KC_UN
      value:
    - name: KC_PW
      value:
    - name: KC_URL
      value:
    - name: KC_CLIENT_ID
      value:
    - name: HMDA_ENV
      value:
    - name: MM_HOOK
      value:
    schedule: "*/5 * * * *"
    command: ["/bin/sh"]
    args:
      -  "-c"
      - ./scripts/newmanFilingTest.sh $KC_UN $KC_PW $KC_URL $KC_CLIENT_ID $HOST_FILING $HOST_ADMIN $HOST_PUBLIC $HMDA_ENV $MM_HOOK
    resources:
      limits:
        cpu: 50m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 256Mi
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: Never