apiVersion: v1
kind: ConfigMap
metadata:
  name: pgtables-configmap
data:
  pgtable.tsTableName: "hmda_beta_user.transmittalsheet2019"
  pgtable.larTableName: "hmda_beta_user.loanapplicationregister2019"
  pgtable.historyTableName: "hmda_beta_user.submission_history2019"
