kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pod-reader-binding
  namespace: default
  labels:
      rbac.authorization.k8s.io/aggregate-to-admin: "true"
subjects:
  - kind: ServiceAccount
    name: hmda-service-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io