apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hmda
  name: hmda
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hmda
  template:
    metadata:
      labels:
        app: hmda
        actorSystemName: hmda2
    spec:
      serviceAccountName: hmda-service-account
      containers:
      - name: hmda
        image: jmarin/hmda-platform:2.0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: HMDA_RUNTIME_MODE
          value: kubernetes
        - name: HOST_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        livenessProbe:
          tcpSocket:
            port: 19999
        ports:
        # akka remoting
        - name: remoting
          containerPort: 2551
          protocol: TCP
        # akka-management bootstrap
        - name: bootstrap
          containerPort: 8558
          protocol: TCP
        # external http
        - name: akka-mgmt-http
          containerPort: 19999
          protocol: TCP
