apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hmda
  name: hmda
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hmda
  template:
    metadata:
      labels:
        app: hmda
        actorSystemName: {{ .Values.hmda.actorSystemName }}
    spec:
      serviceAccountName: {{ .Values.service.account.name }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: HMDA_RUNTIME_MODE
          value: {{ .Values.hmda.runtimeMode }}
        - name: HOST_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        livenessProbe:
          tcpSocket:
            port: 19999
        ports:
        # akka remoting
        - name: remoting
          containerPort: 2551
          protocol: TCP
        # akka-management bootstrap
        - name: bootstrap
          containerPort: 8558
          protocol: TCP
        # external http
        - name: akka-mgmt-http
          containerPort: 19999
          protocol: TCP
