kind: Service
apiVersion: v1
metadata:
  name: hmda-bootstrap
spec:
  # by setting the clusterIp to None we are a "headless service"
  # and thus the svc ("service") DNS record for the single IP but the IPs of all nodes that we select
  #
  # In other words:
  #  POD=$(kubectl get pods | grep hmda | grep Running | head -n1 | awk '{ print $1 }')
  #  $ kubectl exec -it $POD -- nslookup hmda-service.default.svc.cluster.local
  #  Server:		10.0.0.10
  #  Address:	10.0.0.10#53
  #
  #  Name:	hmda-service.default.svc.cluster.local
  #  Address: 172.17.0.7
  #  Name:	hmda-service.default.svc.cluster.local
  #  Address: 172.17.0.8
  #  Name:	hmda-service.default.svc.cluster.local
  clusterIP: None
  selector:
    app: hmda
  ports:
  - protocol: TCP
    port: 8558
    targetPort: 8558

---
kind: Service
apiVersion: v1
metadata:
  name: hmda-api
spec:
  selector:
    app: hmda
  type: NodePort
  ports:
  - name: filing
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: admin
    protocol: TCP
    port: 8081
    targetPort: 8081
  - name: public
    protocol: TCP
    port: 8082
    targetPort: 8082
  - name: cluster
    protocol: TCP
    port: 19999
    targetPort: 19999