apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak
  name: keycloak-http
  namespace: default
spec:
  type : ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: keycloak
