---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: ratespread-calculator
  type: NodePort
  ports:
  - name: {{ .Values.ratespread.name }}
    protocol: {{ .Values.ratespread.protocol }}
    port: {{ .Values.ratespread.port }}
    targetPort: {{ .Values.ratespread.port }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador-ratespread-calculator
  name: ambassador-ratespread-calculator
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v0
      kind: Mapping
      name: hmda_ratespread_mapping
      prefix: /public/
      service: {{ .Values.service.name }}:{{ .Values.ratespread.port }}
spec:
  type: {{ .Values.ambassador.service.type }}
  ports:
  - name: ambassador-ratespread-calculator
    port: {{ .Values.ambassador.port }}
    targetPort: {{ .Values.ambassador.port }}
  selector:
    service: ambassador-ratespread-calculator
