apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-inst-api-config"
data:
  instapi.postgres_host: "{{ .Values.postgresql.host }}"
  cassandra-hosts: "{{ .Values.cassandra.hosts }}"
  postgres.ssl: "{{ .Values.postgresql.ssl }}"
