version: "3.1"
services:
  hmda-newman:
    container_name: hmda-newman-one
    image: hmda/newman-automation:latest
    environment:
      - KC_UN=${KC_UN}
      - KC_PW=${KC_PW}
      - KC_URL=${KC_URL}
      - KC_CLIENT_ID=${KC_CLIENT_ID}
      - HOST_FILING=${HOST_FILING}
      - HOST_ADMIN=${HOST_ADMIN}
      - HOST_PUBLIC=${HOST_PUBLIC}
      - HMDA_ENV=${HMDA_ENV}
      - MM_HOOK=${MM_HOOK}
      - YEAR=2019
    command:
      ./scripts/run_one_newman.sh
    volumes:
      - ./src:/etc/newman

