---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "census.fullname" . }}
  labels:
    app: {{ template "census.name" . }}
    chart: {{ template "census.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
    app: {{ template "census.name" . }}
    release: {{ .Release.Name }}


---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "census.fullname" . }}-grpc
  labels:
    app: {{ template "census.fullname" . }}
    chart: {{ template "census.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.grpc.type }}
  ports:
    - port: {{ .Values.grpc.port }}
      targetPort: {{ .Values.grpc.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.grpc.name }}
  selector:
    app: {{ template "census.name" . }}
    release: {{ .Release.Name }}
