apiVersion: v1
kind: Service
metadata:
  name: ambassador
  namespace: jenkins-system
  labels:
    app: ambassador
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Module
      name:  ambassador
      cofig:
        ambassador_id: ambassador-jenkins-3  
spec:
  type: NodePort
  ports:
   - port: 80
     nodePort: 30300
  selector:
    service: ambassador
