# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
jobs:
  # data browser integration tests
  - name: newmen-data-browser
    image:
      repository: hmda/newman-tests
      tag: dev
      imagePullPolicy: Always
    # optional env vars
    env:
    - name: HOST_DATA_BROWSER
      value:
    schedule: "*/5 * * * *"
    command: ["/bin/bash"]
    args:
      -  "-c"
      - NODE_OPTIONS="--max_old_space_size=2048" ./node_modules/.bin/newman run data-browser/data-browser-api-test.json -d data-browser/data-browser-api-config.json --env-var db-api=$HOST_DATA_BROWSER  --timeout-script 500000
    resources:
      limits:
        cpu: 50m
        memory: 2048Mi
      requests:
        cpu: 50m
        memory: 2048Mi
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: Never