---
apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-configmap
data:
  aws-environment: "{{ .Values.aws.environment }}"
  s3-public-bucket: "{{ .Values.aws.bucket }}"
  aws-region: "{{ .Values.aws.region }}"
